
import turtle

plane = turtle.Turtle()

plane.speed(25)
bgg=turtle.Screen()
bgg.bgcolor("lightblue")

plane.penup()
plane.goto(0, -50)
plane.pendown()
plane.color("white")
plane.begin_fill()
plane.forward(200)
plane.left(90)
plane.forward(25)
plane.left(90)
plane.forward(200)
plane.left(90)
plane.forward(25)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(95,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(135,-55)
plane.forward(20)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(135,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(145,-55)
plane.forward(20)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(145,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(155,-55)
plane.forward(20)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(155,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(165,-55)
plane.forward(20)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(165,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(175,-55)
plane.forward(20)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(175,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(5)
    plane.left(90)
plane.end_fill()

plane.penup()
plane.color("blue")
plane.goto(200,-55)
plane.forward(10)
plane.pendown()
plane.begin_fill()
for _ in range(4):
    plane.forward(15)
    plane.left(90)
plane.end_fill()

plane.penup() 
plane.goto(25,-50)
plane.color("white")
plane.begin_fill()
plane.pendown()
plane.right(90)
plane.forward(25)
plane.right(85)
plane.forward(25)
plane.right(100)
plane.forward(25)
plane.right(80)
plane.forward(25)
plane.pendown()
plane.end_fill()


turtle.exitonclick() 